// <auto-generated />
namespace ProjectManager.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AppUser_Role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppUser_Role));
        
        string IMigrationMetadata.Id
        {
            get { return "201601170251141_AppUser_Role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
